version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env.docker
    depends_on:
      - backend
